// MCP 配置生成：根据当前运行位置动态生成 Agent 可复制的 MCP 配置。
// 关键目标：不写死安装目录；兼容中文路径；打包 exe 后仍可运行。
const { app } = require('electron')
const fs = require('fs')
const path = require('path')
const settings = require('./settings')

function psQuote(s) {
  return `'${String(s).replace(/'/g, "''")}'`
}

function ensureRuntimeFiles() {
  const dir = path.join(app.getPath('userData'), 'mcp')
  fs.mkdirSync(dir, { recursive: true })

  const appPath = app.getAppPath()
  const serverSource = path.join(appPath, 'src', 'mcp', 'server.mjs')
  const serverTarget = path.join(dir, 'server.mjs')
  if (fs.existsSync(serverSource)) {
    fs.copyFileSync(serverSource, serverTarget)
  }

  const electronExe = process.execPath
  const api = `http://127.0.0.1:${settings.get('server.port')}/api/call`
  const nodePathCandidates = [
    path.join(appPath, 'node_modules'),
    path.join(process.resourcesPath || '', 'app.asar', 'node_modules'),
    path.join(process.resourcesPath || '', 'app', 'node_modules')
  ].filter(Boolean)

  const scriptPath = path.join(dir, 'mcp.ps1')
  const script = `# Auto-generated by 牛马联盟. Do not edit manually; it is refreshed on app startup.\n` +
`# UTF-8 safe MCP launcher. Works with Chinese paths and packaged Electron.\n` +
`param(\n` +
`  [string]$Api = ${psQuote(api)}\n` +
`)\n` +
`$ErrorActionPreference = 'Stop'\n` +
`chcp 65001 > $null\n` +
`$OutputEncoding = [System.Text.Encoding]::UTF8\n` +
`[Console]::OutputEncoding = [System.Text.Encoding]::UTF8\n` +
`[Console]::InputEncoding = [System.Text.Encoding]::UTF8\n` +
`$env:PYTHONIOENCODING = 'utf-8'\n` +
`$env:NMLM_API = $Api\n` +
`$env:ELECTRON_RUN_AS_NODE = '1'\n` +
`$env:NODE_PATH = ${psQuote(nodePathCandidates.join(path.delimiter))}\n` +
`& ${psQuote(electronExe)} ${psQuote(serverTarget)}\n`

  fs.writeFileSync(scriptPath, script, 'utf8')
  return { dir, scriptPath, serverPath: serverTarget, electronExe, api }
}

function getMcpConfig() {
  const runtime = ensureRuntimeFiles()
  const config = {
    mcpServers: {
      'nmlm-todo': {
        command: 'powershell',
        args: ['-ExecutionPolicy', 'Bypass', '-NoProfile', '-File', runtime.scriptPath],
        env: {
          NMLM_API: runtime.api
        }
      }
    }
  }
  return {
    ok: true,
    ...runtime,
    config,
    configJson: JSON.stringify(config, null, 2)
  }
}

module.exports = { ensureRuntimeFiles, getMcpConfig }
