// MCP 配置生成：以标准 stdio command/args/env 为真值，再适配不同 Agent 的配置外壳。
// MCP server 零外部依赖，可由 Node 或 ELECTRON_RUN_AS_NODE 直接运行。
const { app } = require('electron')
const { spawn } = require('child_process')
const fs = require('fs')
const path = require('path')
const settings = require('./settings')
const { buildProfiles } = require('./mcpProfiles')

function psQuote(s) {
  return `'${String(s).replace(/'/g, "''")}'`
}

function ensureRuntimeFiles() {
  const dir = path.join(app.getPath('userData'), 'mcp')
  fs.mkdirSync(dir, { recursive: true })

  const appPath = app.getAppPath()
  const serverSource = path.join(appPath, 'src', 'mcp', 'server.mjs')
  const serverTarget = path.join(dir, 'server.mjs')
  if (!fs.existsSync(serverSource)) throw new Error(`MCP 服务文件不存在：${serverSource}`)
  fs.copyFileSync(serverSource, serverTarget)

  const electronExe = process.execPath
  const api = `http://127.0.0.1:${settings.get('server.port')}/api/call`
  const scriptPath = path.join(dir, 'mcp.ps1')
  const script = `# Auto-generated by 牛马联盟. This is a legacy PowerShell fallback.\n` +
`param([string]$Api = ${psQuote(api)})\n` +
`$ErrorActionPreference = 'Stop'\n` +
`chcp 65001 > $null\n` +
`$OutputEncoding = [System.Text.Encoding]::UTF8\n` +
`[Console]::OutputEncoding = [System.Text.Encoding]::UTF8\n` +
`[Console]::InputEncoding = [System.Text.Encoding]::UTF8\n` +
`$env:NMLM_API = $Api\n` +
`$env:ELECTRON_RUN_AS_NODE = '1'\n` +
`& ${psQuote(electronExe)} ${psQuote(serverTarget)}\n`
  fs.writeFileSync(scriptPath, script, 'utf8')

  const launcher = {
    command: electronExe,
    args: [serverTarget],
    env: {
      ELECTRON_RUN_AS_NODE: '1',
      NMLM_API: api
    }
  }
  return { dir, scriptPath, serverPath: serverTarget, electronExe, api, launcher }
}

function getMcpConfig() {
  const runtime = ensureRuntimeFiles()
  const profiles = buildProfiles(runtime.launcher)
  return {
    ok: true,
    ...runtime,
    profiles,
    profileOptions: profiles.map(({ id, label }) => ({ id, label })),
    config: profiles[0].config,
    configJson: profiles[0].configJson
  }
}

function testMcpConnection() {
  const runtime = ensureRuntimeFiles()
  return new Promise((resolve) => {
    const startedAt = Date.now()
    const child = spawn(runtime.launcher.command, runtime.launcher.args, {
      env: { ...process.env, ...runtime.launcher.env },
      stdio: ['pipe', 'pipe', 'pipe'],
      windowsHide: true
    })
    let stdout = ''
    let stderr = ''
    let settled = false
    let toolCount = 0
    let initialized = false
    let apiConnected = false

    const finish = (result) => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      try { child.stdin.end() } catch (_) {}
      try { child.kill() } catch (_) {}
      resolve({ elapsedMs: Date.now() - startedAt, ...result })
    }

    const inspectLines = () => {
      const lines = stdout.split(/\r?\n/)
      stdout = lines.pop() || ''
      for (const line of lines) {
        if (!line.trim()) continue
        let message
        try { message = JSON.parse(line) } catch (_) { return finish({ ok: false, error: `MCP 输出不是合法 JSON-RPC：${line.slice(0, 160)}` }) }
        if (message.id === 1 && message.result?.serverInfo?.name === 'nmlm') initialized = true
        if (message.id === 2 && Array.isArray(message.result?.tools)) toolCount = message.result.tools.length
        if (message.id === 3) {
          apiConnected = !message.result?.isError
          if (!initialized || !toolCount) return finish({ ok: false, error: 'MCP 握手成功，但工具列表不完整' })
          if (!apiConnected) {
            const detail = message.result?.content?.[0]?.text || '桌面 API 调用失败'
            return finish({ ok: false, error: detail, initialized, toolCount, apiConnected })
          }
          return finish({ ok: true, initialized, toolCount, apiConnected })
        }
      }
    }

    child.stdout.setEncoding('utf8')
    child.stderr.setEncoding('utf8')
    child.stdout.on('data', (chunk) => { stdout += chunk; inspectLines() })
    child.stderr.on('data', (chunk) => { stderr += chunk })
    child.on('error', (error) => finish({ ok: false, error: `无法启动 MCP：${error.message}` }))
    child.on('exit', (code) => {
      if (!settled) finish({ ok: false, error: `MCP 进程提前退出（code ${code}）${stderr ? `：${stderr.trim().slice(0, 300)}` : ''}` })
    })

    const timer = setTimeout(() => finish({ ok: false, error: `MCP 连接测试超时${stderr ? `：${stderr.trim().slice(0, 300)}` : ''}` }), 6000)
    const requests = [
      { jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2024-11-05', capabilities: {}, clientInfo: { name: 'nmlm-self-test', version: '1.0.0' } } },
      { jsonrpc: '2.0', method: 'notifications/initialized', params: {} },
      { jsonrpc: '2.0', id: 2, method: 'tools/list', params: {} },
      { jsonrpc: '2.0', id: 3, method: 'tools/call', params: { name: 'nmlm_task_current', arguments: {} } }
    ]
    child.stdin.write(`${requests.map((item) => JSON.stringify(item)).join('\n')}\n`)
  })
}

module.exports = { ensureRuntimeFiles, getMcpConfig, testMcpConnection }
